bbc/blogs-frontend

src/BlogsService/Domain/ValueObject/Comments.php
src/Controller/AuthorIndexAtoZController.php
src/Controller/AuthorShowAtoZController.php
src/Controller/AuthorShowController.php
src/Controller/BaseController.php
src/Controller/BlogShowController.php
src/Controller/BlogsBaseController.php
src/Controller/HomeController.php
src/Controller/PostByDateController.php
src/Controller/PostByDateRedirectController.php
src/Controller/PostShowController.php
src/Controller/TagIndexController.php
src/Controller/TagShowController.php
src/ValueObject/AnalyticsCounterName.php
src/ValueObject/IstatsAnalyticsLabels.php
tests/BaseWebTestCase.php
tests/BlogsService/Domain/ValueObject/CommentsTest.php
tests/Controller/HomeControllerTest.php
tests/ValueObject/AnalyticsCounterNameTest.php
tests/ValueObject/IstatsAnalyticsLabelsTest.php

https://jira.dev.bbc.co.uk/browse/BLOGS-1320
I think this is everything. Is there anything I've missed?

BLOGS-1320 Adding PHP side of iStats

---

composer.json
composer.lock
symfony.lock

Updated packages so that none are pointing at Beta or dev-master.
Changed minimum stability to stable.
Binned symfony/lts as I don't think we need it.

Stablising Composer

---

resources/js/smp.js
src/Controller/BlogsBaseController.php
src/Ds/Post/ContentBlock/ClipsBlock/ClipsBlockPresenter.php
templates/blogs_base.html.twig

I just saw this when I was checking why test was accessing the wrong env yesterday. This isn't actually related to that, I just saw we were doing the same thing 2 different ways and thought it could be tidied up. 
I havent tested this. It will probably explode. Please make sure it doesn't if you're going to merge it.

Tidy up SMP playlist.json endpoint

---

resources/js/smp.js
src/Controller/BaseController.php
templates/base.html.twig

https://jira.dev.bbc.co.uk/browse/BLOGS-1303
Adding counterName so replicates behaviour of v4.

Blogs-1303 SMP iStats

---

config/services.yaml
src/BlogsService/Mapper/IsiteToDomain/Mapper.php
src/BlogsService/Mapper/IsiteToDomain/PostMapper.php
tests/BlogsService/Mapper/IsiteToDomain/BlogMapperTest.php
tests/BlogsService/Mapper/IsiteToDomain/PostMapperTest.php
tests/mock_data/blogsmetadata_invalidfeatured.xml
tests/mock_data/post_invalidcontentblocks.xml

https://jira.dev.bbc.co.uk/browse/BLOGS-1337

BLOGS-1337 Fix Mappers

---

src/Ds/Molecule/DatePicker/date_picker.html.twig
src/Ds/Post/ContentBlock/ClipsBlock/clips_block.html.twig
src/Ds/Post/ContentBlock/SocialBlock/social_block.html.twig
src/Twig/DesignSystemPresenterExtension.php
src/Twig/GelIconExtension.php
src/Twig/HtmlUtilitiesExtension.php
src/Twig/SmpExtension.php
src/Twig/TranslateAndTimeExtension.php
templates/base.html.twig
templates/blogs_base.html.twig
templates/post/by_date.html.twig

https://jira.dev.bbc.co.uk/browse/BLOGS-1325

BLOGS-1325-Javascript

---

src/Controller/BaseController.php
src/Controller/BlogsBaseController.php
translations/blogs/cy.po

https://jira.dev.bbc.co.uk/browse/BLOGS-1341

BLOGS-1341 - Add Welsh translations

---

composer.json
composer.lock
config/routes.yaml
src/Controller/AbstractBlogFeedController.php
src/Controller/AbstractFeedController.php
src/Controller/AbstractTagFeedController.php
src/Controller/BlogAtomFeedController.php
src/Controller/BlogRssFeedController.php
src/Controller/TagAtomFeedController.php
src/Controller/TagRssFeedController.php
src/Ds/Post/ContentBlock/SocialBlock/SocialBlockPresenter.php
src/Ds/SidebarModule/UpdatesPresenter.php
src/FeedGenerator/FeedGenerator.php
symfony.lock
tests/Ds/Post/ContentBlock/SocialBlockTest.php
tests/Ds/SidebarModule/UpdatesTemplateTest.php
tests/FeedGenerator/FeedGeneratorTest.php

https://jira.dev.bbc.co.uk/browse/BLOGS-1288

BLOGS-1288 Feeds

---

config/routes.yaml
src/Ds/Post/Tags/tags.html.twig
src/Ds/SidebarModule/blog_tags.html.twig
templates/tag/index.html.twig
templates/tag/show.html.twig

Making the tag routes naming consistent with others

Improve tag route naming

---

src/BlogsService/Domain/Post.php
src/Twig/SchemaJsonExtension.php
tests/Builders/PostBuilder.php
tests/Twig/SchemaJsonExtensionTest.php

- Don't try and get Authors name is Author doesn't exist
- Corrected type hints on Post domain object
- Refactor PostBuilder to allow for null Author and Image

Fix JsonSchemaExtension

---

templates/blogs_base.html.twig

Removing the placeholder for this module from the template

Remove Recently Commented Module

---

composer.lock
config/routes.yaml
gulpfile.js
resources/js/blogs-bootstrap.js
resources/js/lazyload.js
src/Controller/CommentsIndexController.php
src/Controller/CommentsPartialController.php
src/Ds/Core/Module/_loader.scss
src/Service/CommentsService.php
templates/base.html.twig
templates/comments/index.html.twig
templates/comments/partial.html.twig
templates/post/show.html.twig

We're now lazyloading the comments module into the post page to avoid caching comments for the same ttl as the page

Lazyload Comments

---

src/Ds/Post/Author/author.html.twig
templates/blog/show.html.twig
templates/home/show.html.twig

Ticket: https://jira.dev.bbc.co.uk/browse/BLOGS-1369

[BLOGS-1369] Helping QA automation

---

src/Ds/Post/PostPreview/post_preview.html.twig
src/Ds/SidebarModule/about.html.twig
src/Ds/SidebarModule/blog_tags.html.twig
src/Ds/SidebarModule/freetext.html.twig
src/Ds/SidebarModule/links.html.twig
src/Ds/SidebarModule/updates.html.twig
templates/post/by_date.html.twig

Ticket: https://jira.dev.bbc.co.uk/browse/BLOGS-1370 (Also adds on a little bit more from https://jira.dev.bbc.co.uk/browse/BLOGS-1369)
These were all requested by QA

[BLOGS-1370] Added extra Blogs automation support

---

composer.lock
src/Kernel.php
symfony.lock

Ticket: https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6456
Ran `composer update symfony/*` and then fixed the one issue that came up (Couldn't load parameters for the comments module).

[PROGRAMMES-6456] Update symfony

---

composer.lock
src/Ds/Post/Author/author.html.twig
src/Ds/Post/PostSummary/post_summary.html.twig
templates/author/index.html.twig
templates/author/show.html.twig

Ticket: https://jira.dev.bbc.co.uk/browse/BLOGS-1369
Hopefully should be everything QA needs

[BLOGS-1369] Adding automation ids

---

src/Ds/Post/PostSummary/post_summary.html.twig
templates/blog/show.html.twig
templates/post/by_date.html.twig
templates/post/show.html.twig
templates/tag/show.html.twig

Ticket: https://jira.dev.bbc.co.uk/browse/BLOGS-1369
This adds in and cleans up the data attributes a bit more at request of QA.

[Blogs-1369] Automation data section hotfix

---

templates/post/show.html.twig

https://jira.dev.bbc.co.uk/browse/BLOGS-1380

BLOGS-1380 Translating post dates

---

src/BlogsService/Mapper/IsiteToDomain/ModuleMapper.php

https://jira.dev.bbc.co.uk/browse/BLOGS-1379
Link:
http://sandbox.bbc.co.uk:83/blogs/demo/entries/58b86893-40c7-46db-bbe3-c0f360080892?__flush_cache=1

[BLOGS-1379] fixed the issue with exception being thrown

---

config/services.yaml
src/Service/CommentsService.php

https://jira.dev.bbc.co.uk/browse/BLOGS-1384

BLOGS-1384 - added comments module version

---

src/Controller/BaseController.php
src/ValueObject/AtiAnalyticsLabels.php

Ticket: 
https://jira.dev.bbc.co.uk/browse/BLOGS-1385

[Blogs-1386] Ati Stats level 1 destination

---

src/ValueObject/AtiAnalyticsLabels.php

Ticket:
https://jira.dev.bbc.co.uk/browse/BLOGS-1386

[BLOGS-1386] added app name

---

config/services.yaml
config/services_test.yaml
phpstan.neon
src/BlogsService/Service/LegacyBlogService.php
src/BlogsService/Service/ServiceFactory.php
src/BlogsService/StubService/LegacyBlogStubService.php
src/EventSubscriber/ArchivedBlogsSubscriber.php
tests/EventSubscriber/ArchivedBlogsSubscriberTest.php

Ticket: https://jira.dev.bbc.co.uk/browse/BLOGS-1381

[BLOGS-1381] Archived blogs magic

---

config/services.yaml
resources/js/third-party.js
src/Ds/Core/Objects/_third-party.scss

Ticket:
https://jira.dev.bbc.co.uk/browse/BLOGS-1394
Same as Bjorn's fix for PROGRAMMES-6892
Link:
https://sandbox.bbc.co.uk:446/blogs/aboutthebbc/entries/963960b7-8ee9-4308-8e26-b89c399e7278

[BLOGS-1394] Instagram not fully shown

---

composer.json
composer.lock
phpstan.neon
src/BlogsService/Mapper/IsiteToDomain/ModuleMapper.php
src/Metrics/Cache/MetricCacheApcu.php
symfony.lock
tests/Ds/Molecule/DatePicker/DatePickerTest.php

I manage to get phpstan to the last version with the most strict checks level.
I have also update composer again

composer update:

---

config/services.yaml
src/EventSubscriber/CacheFlushSubscriber.php
tests/EventSubscriber/CacheFlushSubscriberTest.php

Copy and paste from programmes frontend but with some small improvements sugested by typehinters.
Origina files:
https://github.com/bbc/programmes-frontend/blob/develop/src/EventSubscriber/MonitoringSubscriber.php
https://github.com/bbc/programmes-frontend/blob/develop/tests/EventSubscriber/CacheFlushSubscriberTest.php

Enable flush cache

---

src/Ds/Post/PostSummary/PostSummaryPresenter.php
src/Ds/Post/PostSummary/post_summary.html.twig

Ticket: https://jira.dev.bbc.co.uk/browse/BLOGS-1402

[BLOGS-1402] Fixed all the bugs

---

src/BlogsService/Query/IsiteQuery/GuidQuery.php
src/BlogsService/Repository/PostRepository.php
src/BlogsService/Service/PostService.php
src/Controller/AuthorShowController.php
src/Controller/BaseController.php
src/Controller/CommentsIndexController.php
src/Controller/CommentsPartialController.php
src/Controller/ExceptionController.php
src/Controller/PostShowController.php
src/ValueObject/MetaContext.php
templates/base.html.twig
templates/post/show.html.twig

https://jira.dev.bbc.co.uk/browse/BLOGS-1405

Previews are fun for everybody.

---

src/ValueObject/AtiAnalyticsLabels.php

Ticket: https://jira.dev.bbc.co.uk/browse/BLOGS-1385

[BLOGS-1385] Added level 1 bucket

---

src/Controller/AuthorIndexAtoZController.php
src/Controller/AuthorIndexController.php
src/Controller/AuthorShowAtoZController.php
src/Controller/AuthorShowController.php
src/Controller/BaseController.php
src/Controller/BlogShowController.php
src/Controller/CommentsIndexController.php
src/Controller/HomeController.php
src/Controller/PostByDateController.php
src/Controller/PostShowController.php
src/Controller/TagIndexController.php
src/Controller/TagShowController.php
src/ValueObject/AtiAnalyticsLabels.php
templates/base.html.twig

Ticket: https://jira.dev.bbc.co.uk/browse/BLOGS-1398

[BLOGS-1398] Added chapter one ATI Variable

---

bin/security-checker.sh
composer.lock
src/Twig/DesignSystemPresenterExtension.php
src/Twig/GelIconExtension.php
src/Twig/HtmlUtilitiesExtension.php
src/Twig/SchemaJsonExtension.php
src/Twig/SmpExtension.php
src/Twig/TranslateAndTimeExtension.php

update symfony
update twig deprecations
add security-check script

update vulnerable packages

---

src/Controller/BaseController.php
src/ValueObject/AtiAnalyticsLabels.php

Ticket: https://jira.dev.bbc.co.uk/browse/BLOGS-1397

[BLOGS-1397] Custom variables for ATI Stats

---

src/BlogsService/Domain/Post.php
src/BlogsService/Mapper/IsiteToDomain/Mapper.php
src/BlogsService/Mapper/IsiteToDomain/PostMapper.php
src/BlogsService/Repository/PostRepository.php
src/BlogsService/Service/PostService.php
src/Controller/AbstractBlogFeedController.php
src/Controller/BlogShowController.php
src/Controller/CommentsIndexController.php
src/Controller/PostShowController.php
src/Ds/Post/PostPreview/post_preview.html.twig
src/Ds/Post/PostSummary/post_summary.html.twig
src/FeedGenerator/FeedGenerator.php
src/Helper/ApplicationTimeProvider.php
src/Twig/SchemaJsonExtension.php
templates/post/show.html.twig
tests/BlogsService/Domain/PostTest.php
tests/Builders/PostBuilder.php

https://youtu.be/SII-jhEd-a0?t=178

BLOGS-1407: Fix timezone handling ONCE AND FOR ALL!

---

gulpfile.js

Ticket: https://jira.dev.bbc.co.uk/browse/BLOGS-1410

[BLOGS-1410] Fix blogs gulp not building

---

src/Ds/Post/Author/author.html.twig
src/Ds/Post/SocialBar/social_bar.html.twig
src/Ds/Post/Tags/tags.html.twig
templates/post/show.html.twig

Ticket: https://jira.dev.bbc.co.uk/browse/BLOGS-1413
Let me know what you think

[BLOGS-1413] Publisher events

---

src/Ds/SidebarModule/about.html.twig
src/Ds/SidebarModule/blog_tags.html.twig
src/Ds/SidebarModule/updates.html.twig
tests/Ds/SidebarModule/AboutTemplateTest.php
tests/Ds/SidebarModule/BlogTagsTemplateTest.php

Tested on ATI and seems working fine

BLOGS-1416 Implement "publisher" event tracking for sidebar modules

---

src/Ds/Post/PostSummary/post_summary.html.twig
templates/author/show.html.twig

Ticket: https://jira.dev.bbc.co.uk/browse/BLOGS-1414

[BLOGS-1414] Author page publisher events

---

src/Ds/Post/Author/AuthorPresenter.php
src/Ds/Post/Author/author.html.twig
src/Ds/Post/PostPreview/post_preview.html.twig
src/Ds/Post/PostSummary/post_summary.html.twig
src/Ds/Post/SocialBar/SocialBarPresenter.php
src/Ds/Post/SocialBar/social_bar.html.twig
templates/blog/show.html.twig

https://jira.dev.bbc.co.uk/browse/BLOGS-1415
I tested it and seems fine but I have to open the PR in a bit of a rush becuase I'm going on holidays, please feel free to do any changes and merge when ready

BLOGS-1415 Implement "publisher" event tracking for Blog Index page

---

src/Ds/Post/PostPreview/PostPreviewPresenter.php
src/Ds/Post/PostPreview/post_preview.html.twig
src/Ds/Post/PostSummary/PostSummaryPresenter.php
src/Ds/Post/PostSummary/post_summary.html.twig

read-more was not implemented for PostPreview.
fixed and refactored the way postAuthor is included

BLOGS-1415 QA found issues

---

config/services.yaml

Ticket: https://jira.dev.bbc.co.uk/browse/BLOGS-1388

[BLOGS-1388] Comments ~2~, no, 3!

---

composer.json
composer.lock

reference branding client 3

---

composer.lock

There was some other things worthy of an update, but caching library was the main one

[No ticket] Update minor composer libraries

---

bin/ci-build
bin/test
composer.json
phpstan.neon
project.json

[PROGRAMMES-7165] blogs-frontend PHP 7.3 upgrade

---

src/Ds/Core/Module/_comments.scss

Ticket: https://jira.dev.bbc.co.uk/browse/BLOGS-1424

[BLOGS-1424] Fix blogs comments link highlighting issue

---

src/Controller/AuthorIndexAtoZController.php
src/Controller/AuthorIndexController.php
src/Controller/AuthorShowAtoZController.php
src/Controller/AuthorShowController.php
src/Controller/BlogShowController.php
src/Controller/CommentsIndexController.php
src/Controller/Helpers/Services/AtiAnalyticsHelper.php
src/Controller/HomeController.php
src/Controller/PostByDateController.php
src/Controller/PostShowController.php
src/Controller/TagIndexController.php
src/Controller/TagShowController.php

Ticket: https://jira.dev.bbc.co.uk/browse/BLOGS-1422

[BLOGS-1422] Set blogs ATI content labels to unlock UAS on comments

---

src/Controller/AuthorShowController.php
src/Controller/CommentsIndexController.php

Ticket: https://jira.dev.bbc.co.uk/browse/BLOGS-1422

[BLOGS-1422] Add ATI guid to comments and author pages

---

src/Service/CommentsService.php

Ticket: https://jira.dev.bbc.co.uk/browse/PROGRAMMES-7271
This doesn't include the CSS fixes at the moment (and may never do, time dependent).

[PROGRAMMES-7271] The final countdown
